# Generated by Django 5.1 on 2024-09-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='firstRegistration',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='phoneNumber',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
