# Generated by Django 5.1 on 2024-09-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicle_firstregistration_vehicle_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
