# Generated by Django 5.1 on 2024-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vehicle_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='numOfDoors',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
