# Generated by Django 5.1 on 2024-09-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle_numofdoors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], default=None, max_length=50, null=True),
        ),
    ]
