# Generated by Django 5.1 on 2024-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vehicle_vehicletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='numOfDoors',
            new_name='doors',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exteriorColor',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuelType',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='images',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspectionValidUntil',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interiorColor',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owners',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicleShape',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='yearOfProduction',
            field=models.DateField(default=None, null=True),
        ),
    ]
