# Generated by Django 5.1 on 2024-09-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_numofdoors_vehicle_doors_vehicle_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='images',
            field=models.JSONField(default=dict),
        ),
    ]
