# Generated by Django 5.1 on 2024-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_vehicle_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
