# Generated by Django 5.1 on 2024-09-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_vehicle_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
