# Generated by Django 5.1 on 2024-09-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_vehicle_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='exteriorColor',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuelType',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='inspectionValidUntil',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='interiorColor',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleShape',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='yearOfProduction',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='properties',
            field=models.JSONField(default=None, null=True),
        ),
    ]
