# Generated by Django 5.1 on 2024-09-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_vehicle_doors_remove_vehicle_engine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='power',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='firstRegistration',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
