# Generated by Django 5.1 on 2024-09-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_vehicle_power_vehicle_engine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='properties',
            new_name='other',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
