# Generated by Django 5.1 on 2024-09-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_properties_vehicle_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
