# Generated by Django 5.1 on 2024-09-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_vehicle_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
