# Generated by Django 5.1 on 2024-09-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_vehicle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='engine',
            new_name='power',
        ),
    ]
